### ISSUE TITLE
Renomear configurações do template e modificar valores padrão

### ISSUE THREAD

**Issue by jrdncstr** [dsoaress/abnt-pandoc#1]
Como desconhecia o significado de "entrelinhas" e "indentação" no contexto do template, precisei ler o arquivo latex e pesquisar o que os comandos \parindent e \setstretch fazem.

Desta forma, sugiro alterar os usos das palavras para nomenclatura mais usual da ABNT:

entrelinhas -> espaçamento
indentação -> recuo do início do parágrafo

Além disso, é razoável usar os padrões da ABNT para esses valores:

espaçamento: 1.5
recuo do início do parágrafo: 1.25cm

**Comment by dsoaress** [comment]
Oi,

Quando eu decidi esses nomes, tentei ao máximo manter nomes curtos e que fossem representativos por si só. Não acho que *espaçamento* seja mais representativo que *entrelinhas*. Talvez chamar de "espaçamento-entrelinhas" e/ou colocar um comentário no arquivo *_config* deixando mais claro do que se trata seja mais interessante. Ex.:

```yml
# Espaçamento entrelinhas
entrelinhas: 1.5
```

ou

```yml
# Espaçamento entrelinhas
espaçamento-entrelinhas: 1.5
```

Agora sua sugestão de usar *"recuo do início do parágrafo"* não me parece bom porque é muito grande e precisaria ser algo como `recuo-do-início-do-parágrafo` pois não se pode ter espaços. Talvez seja o caso de também colocar um comentário explicando melhor do que se trata. Ex.:

```yml
# Recuo do início do parágrafo
indentação: 1.3cm
```

ou ainda

```yml
# Recuo do início do parágrafo
recuo: 1.3cm
```

Por fim, sim, é razoável deixar o espaçamento em 1.5 por padrão (1.3 era birra minha porque acho 1.5 feio).(1) Mas a indentação de 1,25cm não é uma norma. A ABNT só diz que a primeira linha de cada parágrafo deve ser recuada, sem definir um tamanho. Aí ficou a cargo de cada universidade definir essa regra. A minha, por exemplo, diz que tem que ser de 3cm, uma monstruosidade.

O que acha?

(1) É bom lembrar que a NBR 6022:2018 (norma para artigos acadêmicos) definiu o espaçamento entrelinhas em 1 (espaçamento simples) para todo o corpo do texto. Mas eu duvido que essa norma irá se popularizar um dia.

**Comment by jrdncstr** [comment]
> ```yaml
> # Espaçamento entrelinhas
> entrelinhas: 1.5
> ```

> ```yaml
> # Recuo do início do parágrafo
> recuo: 1.3cm
> ```

Adicionar comentários é suficiente e elegante. Porém, no caso do recuo, ainda acredito que valha a pena mudar o nome da configuração pois o uso de "recuo", termo mais comum no contexto da ABNT<sup>1</sup>, evita possíveis confusões, já que pra mim a palavra "indentação" remete diretamente a código e programação.

Sobre os padrões, acredito que não importam muito se for claro o que a configuração altera.

[1]: Comparar os resultados de https://www.google.com/search?q=indenta%C3%A7%C3%A3o+abnt com os resultados de https://www.google.com/search?q=recuo+abnt. Um dos resultados principais da primeira busca (http://www2.eca.usp.br/etam/ivencontro/templates/normas_eitam4.pdf) parece utilizar o termo indentação para se referir a recuo e margens de forma indiscriminada (?!).

**Comment by dsoaress** [comment]
Por mim está perfeito. Manda uma PR com as alterações.
