### ISSUE TITLE
Erro ao gerar PDF no Windows 10

### ISSUE THREAD

**Issue by vitorcalvi** [dsoaress/abnt-pandoc#4]
Dainel, tudo bem?! Estou buscando uma solução simples e rápida para meu Relatório Técnico (TCC). Achei seu repositório. No caso, o seu padrão está para Artigo científico. No https://www.abntex.net.br/ tem o modelo para Relatório tecnico. Creio que terei que criar o template depois. Ainda não sei fazer.

Estou tentando gerar o PDF no Windows 10 porém sem sucesso. Segue abaixo o erro:
```shell
Error producing PDF.
! LaTeX Error: Environment CSLReferences undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.598 \begin{CSLReferences}
```

Segue o comando no Windows
```shell
pandoc -s --filter C:\Ruby30-x64\bin\pandoc_abnt.bat --citeproc --bibliography=bibliografia.bib --csl C:\temp\abnt-pandoc\.github\workflows\abnt.csl --template .github\workflows\tecnico.tex _config.md 00-introdução.md 01-cap1.md 02-cap2.md 03-considerações-finais.md .github\workflows\referencias.md -o TRABALHO.pdf --pdf-engine=xelatex
```

**Comment by dsoaress** [comment]
Oi Vitor, tem uns meses que não atualizo a versão do Pandoc nesse repositório, você provavelmente está com a versão mais recente do software. Houveram alguns _breaking changes_ na geração de referências bibliográficas e ainda não tive tempo de investigar o que mudou. 

Com a versão 2.9.1.1 do Pandoc funciona perfeitamente (é a que tenho instalada localmente e é a que está no _workflow_ de conversão aqui do repositório), você pode tentar instalar essa versão ou utilizar a conversão automática via GitHub Actions como descrevo no Readme (criar tags das alterações e deixar o GitHub gerar os PDFs por você).

Quanto ao abnTeX2, meu template não é compatível com ele. Você pode tentar outro projeto chamado [Limarka](https://github.com/abntex/limarka) que é baseado no abnTeX2 ou criar um template novo, mas isso vai te exigir um domínio grande de LaTeX.

Sendo bastante franco, eu não sei se vale a pena. O que eu tenho feito é escrever em Markdown e gerar, via Pandoc, um DOCX estruturado para alterar a estilização no Word quando o texto está finalizado e pronto para submissão. As alterações de estilo via LaTeX são muito chatas de se fazer, eu perdi semanas para fazer coisas simples.

**Comment by vitorcalvi** [comment]
Valeu Daniel, muito obrigado pela resposta. Concordo com você, eu gostei da forma como fez porque é simples, rápido e prático.

Dei uma olhada no Limarka, o projeto é excelente, caso adote, teria uma pequena curva de aprendizagem, não estou buscando isso no momento. Eu gostaria de algo igual o seu projeto, somente redigir em MD e Converter. 

Estou inclinado a criar um template novo e exportar conforme seu projeto. Eu olhei o arquivo Relatorio Técnico.tex, já está bem definido as "coisas" nele. Seria basicamente uma adaptação ao padrão do seu projeto.

O que você acha?
Muito Obrigado
